package com.example.campusmarket.warranty.application;

import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Profile;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

/** 质保卖家 72 小时、管理员 7/14 天截止调度；领取使用数据库时间和 token fencing。 */
@Component @Profile("!test") @EnableScheduling
@ConditionalOnProperty(prefix="campus.market.warranty.deadline",name="enabled",havingValue="true",matchIfMissing=true)
public final class WarrantyDeadlineScheduler {
    private final JdbcTemplate jdbc; private final TransactionTemplate tx; private final String owner="warranty-deadline-"+UUID.randomUUID();
    public WarrantyDeadlineScheduler(JdbcTemplate jdbc,org.springframework.transaction.PlatformTransactionManager manager){this.jdbc=Objects.requireNonNull(jdbc);this.tx=new TransactionTemplate(Objects.requireNonNull(manager));}
    @Scheduled(initialDelayString="${campus.market.warranty.deadline.initial-delay-ms:0}",fixedDelayString="${campus.market.warranty.deadline.fixed-delay-ms:1000}") public void dispatch(){runOnce(50);}
    public int runOnce(int limit){if(limit<=0||limit>1000)throw new IllegalArgumentException("批量大小无效");List<UUID> ids=jdbc.query("SELECT id FROM warranty_deadline_claim WHERE due_at<=CURRENT_TIMESTAMP(6) AND (status='NEW' OR (status='PROCESSING' AND lease_until<=CURRENT_TIMESTAMP(6))) ORDER BY due_at,id LIMIT ?",(rs,n)->UUID.fromString(rs.getString(1)),limit);int done=0;for(UUID id:ids){String token=UUID.randomUUID().toString();if(jdbc.update("UPDATE warranty_deadline_claim SET status='PROCESSING',owner_id=?,claim_token=?,lease_until=DATE_ADD(CURRENT_TIMESTAMP(6),INTERVAL 30 SECOND),attempt_count=attempt_count+1,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND due_at<=CURRENT_TIMESTAMP(6) AND (status='NEW' OR (status='PROCESSING' AND lease_until<=CURRENT_TIMESTAMP(6)))",owner,token,id.toString())==1&&process(id,token))done++;}return done;}
    public int runOne(UUID caseId){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM warranty_deadline_claim WHERE warranty_case_id=?",Integer.class,caseId.toString());if(n==null||n==0)return 0;return runOnce(1000);}
    private boolean process(UUID id,String token){try{return Boolean.TRUE.equals(tx.execute(s->{Claim c=jdbc.query("SELECT warranty_case_id,deadline_type,owner_id,claim_token,lease_until FROM warranty_deadline_claim WHERE id=? FOR UPDATE",rs->rs.next()?new Claim(UUID.fromString(rs.getString(1)),rs.getString(2),rs.getString(3),rs.getString(4),rs.getTimestamp(5).toInstant()):null,id.toString());Instant now=dbNow();if(c==null||!owner.equals(c.owner())||!token.equals(c.token())||!c.lease().isAfter(now))return false;CaseRow row=jdbc.query("SELECT status,seller_deadline,admin_deadline,hard_deadline FROM warranty_case WHERE id=? FOR UPDATE",rs->rs.next()?new CaseRow(rs.getString(1),ts(rs.getTimestamp(2)),ts(rs.getTimestamp(3)),ts(rs.getTimestamp(4))):null,c.caseId().toString());if(row==null)return complete(id,token);if("SELLER_RESPONSE".equals(c.type())){if(now.isBefore(row.seller()))return defer(id,token,row.seller());if("OPEN".equals(row.status())){jdbc.update("UPDATE warranty_case SET status='UNDER_REVIEW',admin_deadline=DATE_ADD(CURRENT_TIMESTAMP(6),INTERVAL 7 DAY),hard_deadline=DATE_ADD(CURRENT_TIMESTAMP(6),INTERVAL 14 DAY),version=version+1,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND status='OPEN'",c.caseId().toString());arm(c.caseId());}}else if("ADMIN_SLA".equals(c.type())){if(row.admin()==null||now.isBefore(row.admin()))return defer(id,token,row.admin()==null?now.plusSeconds(1):row.admin());jdbc.update("UPDATE warranty_case SET status=CASE WHEN status IN ('OPEN','SELLER_RESPONDED','UNDER_REVIEW') THEN 'ESCALATED' ELSE status END,admin_sla_alerted_at=COALESCE(admin_sla_alerted_at,CURRENT_TIMESTAMP(6)),updated_at=CURRENT_TIMESTAMP(6) WHERE id=?",c.caseId().toString());}else if("HARD_DEADLINE".equals(c.type())){if(row.hard()==null||now.isBefore(row.hard()))return defer(id,token,row.hard()==null?now.plusSeconds(1):row.hard());jdbc.update("UPDATE warranty_case SET status=CASE WHEN status IN ('OPEN','SELLER_RESPONDED','UNDER_REVIEW') THEN 'ESCALATED' ELSE status END,updated_at=CURRENT_TIMESTAMP(6) WHERE id=?",c.caseId().toString());}return complete(id,token);}));}catch(RuntimeException e){jdbc.update("UPDATE warranty_deadline_claim SET status='NEW',owner_id=NULL,claim_token=NULL,lease_until=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND owner_id=? AND claim_token=? AND lease_until>CURRENT_TIMESTAMP(6)",id.toString(),owner,token);return false;}}
    private void arm(UUID caseId){Instant now=dbNow();jdbc.update("UPDATE warranty_deadline_claim SET due_at=CASE deadline_type WHEN 'ADMIN_SLA' THEN ? WHEN 'HARD_DEADLINE' THEN ? ELSE due_at END,status=CASE WHEN deadline_type IN ('ADMIN_SLA','HARD_DEADLINE') THEN 'NEW' ELSE status END,updated_at=? WHERE warranty_case_id=? AND deadline_type IN ('ADMIN_SLA','HARD_DEADLINE')",Timestamp.from(now.plusSeconds(7*86400L)),Timestamp.from(now.plusSeconds(14*86400L)),Timestamp.from(now),caseId.toString());}
    private boolean defer(UUID id,String token,Instant due){return jdbc.update("UPDATE warranty_deadline_claim SET status='NEW',due_at=?,owner_id=NULL,claim_token=NULL,lease_until=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND status='PROCESSING' AND owner_id=? AND claim_token=? AND lease_until>CURRENT_TIMESTAMP(6)",Timestamp.from(due),id.toString(),owner,token)==1;}
    private boolean complete(UUID id,String token){return jdbc.update("UPDATE warranty_deadline_claim SET status='COMPLETED',completed_at=CURRENT_TIMESTAMP(6),owner_id=NULL,claim_token=NULL,lease_until=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE id=? AND status='PROCESSING' AND owner_id=? AND claim_token=? AND lease_until>CURRENT_TIMESTAMP(6)",id.toString(),owner,token)==1;}
    private Instant dbNow(){return jdbc.queryForObject("SELECT CURRENT_TIMESTAMP(6)",Timestamp.class).toInstant();}private static Instant ts(Timestamp t){return t==null?null:t.toInstant();}
    private record Claim(UUID caseId,String type,String owner,String token,Instant lease){} private record CaseRow(String status,Instant seller,Instant admin,Instant hard){}
}
