CREATE TABLE trade_order (
    id CHAR(36) NOT NULL,
    buyer_id CHAR(36) NOT NULL,
    seller_id CHAR(36) NOT NULL,
    listing_id CHAR(36) NOT NULL,
    listing_title_snapshot VARCHAR(200) NOT NULL,
    listing_description_snapshot TEXT NOT NULL,
    unit_price_fen BIGINT NOT NULL,
    quantity INT NOT NULL,
    total_amount_fen BIGINT NOT NULL,
    warranty_days INT,
    warranty_scope_snapshot TEXT,
    manufacturer_warranty_proof_snapshot TEXT,
    manufacturer_warranty_expires_at TIMESTAMP(6),
    payment_deadline TIMESTAMP(6),
    handoff_deadline TIMESTAMP(6),
    receipt_deadline TIMESTAMP(6),
    t0 TIMESTAMP(6),
    acceptance_deadline TIMESTAMP(6),
    trial_deadline TIMESTAMP(6),
    warranty_deadline TIMESTAMP(6),
    paid_amount_fen BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_trade_order_buyer (buyer_id, created_at),
    KEY idx_trade_order_seller (seller_id, created_at),
    CONSTRAINT ck_trade_order_unit_price CHECK (unit_price_fen >= 0),
    CONSTRAINT ck_trade_order_quantity CHECK (quantity > 0),
    CONSTRAINT ck_trade_order_total CHECK (total_amount_fen >= 0),
    CONSTRAINT ck_trade_order_paid CHECK (paid_amount_fen >= 0 AND paid_amount_fen <= total_amount_fen),
    CONSTRAINT ck_trade_order_warranty_days CHECK (warranty_days IN (30, 90, 180, 365) OR warranty_days IS NULL),
    CONSTRAINT ck_trade_order_status CHECK (status IN ('PENDING_PAYMENT', 'AWAITING_HANDOFF', 'AWAITING_RECEIPT',
        'AFTERSALE_WINDOW', 'DISPUTED', 'REFUNDING_CANCEL', 'CANCELLED', 'REFUNDED', 'SETTLED')),
    CONSTRAINT ck_trade_order_version CHECK (version >= 0),
    CONSTRAINT fk_trade_order_listing FOREIGN KEY (listing_id) REFERENCES listing (id)
);

CREATE TABLE order_command (
    id CHAR(36) NOT NULL,
    order_id CHAR(36),
    actor_id CHAR(36) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    request_hash BINARY(32) NOT NULL,
    status VARCHAR(20) NOT NULL,
    response_utf8 LONGTEXT,
    created_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_command_actor_key (actor_id, idempotency_key),
    CONSTRAINT ck_order_command_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT fk_order_command_order FOREIGN KEY (order_id) REFERENCES trade_order (id)
);

CREATE TABLE order_transition (
    id CHAR(36) NOT NULL,
    order_id CHAR(36) NOT NULL,
    from_status VARCHAR(24),
    to_status VARCHAR(24) NOT NULL,
    actor_id CHAR(36),
    reason VARCHAR(200) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_order_transition_order_time (order_id, occurred_at),
    CONSTRAINT fk_order_transition_order FOREIGN KEY (order_id) REFERENCES trade_order (id)
);

CREATE TABLE order_deadline_claim (
    id CHAR(36) NOT NULL,
    order_id CHAR(36) NOT NULL,
    deadline_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    owner_id VARCHAR(100),
    claim_token VARCHAR(100),
    lease_until TIMESTAMP(6),
    attempt_count INT NOT NULL DEFAULT 0,
    due_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_deadline_order_type (order_id, deadline_type),
    KEY idx_order_deadline_claim (status, due_at, lease_until),
    CONSTRAINT ck_order_deadline_status CHECK (status IN ('NEW', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_order_deadline_attempts CHECK (attempt_count >= 0),
    CONSTRAINT fk_order_deadline_order FOREIGN KEY (order_id) REFERENCES trade_order (id)
);

CREATE TABLE payment_order (
    id CHAR(36) NOT NULL,
    order_id CHAR(36) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    amount_fen BIGINT NOT NULL,
    paid_amount_fen BIGINT NOT NULL DEFAULT 0,
    provider_reference VARCHAR(191),
    status VARCHAR(24) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_order_idempotency (order_id, idempotency_key),
    UNIQUE KEY uk_payment_order_provider_idempotency (provider, idempotency_key),
    UNIQUE KEY uk_payment_order_provider_reference (provider, provider_reference),
    CONSTRAINT ck_payment_order_amount CHECK (amount_fen >= 0),
    CONSTRAINT ck_payment_order_paid CHECK (paid_amount_fen >= 0 AND paid_amount_fen <= amount_fen),
    CONSTRAINT ck_payment_order_status CHECK (status IN ('CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT fk_payment_order_order FOREIGN KEY (order_id) REFERENCES trade_order (id)
);

CREATE TABLE payment_callback_event (
    id CHAR(36) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_event_id VARCHAR(191) NOT NULL,
    payment_order_id CHAR(36),
    payload JSON NOT NULL,
    payload_digest BINARY(32) NOT NULL,
    signature_valid BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    owner_id VARCHAR(100),
    claim_token VARCHAR(100),
    lease_until TIMESTAMP(6),
    attempt_count INT NOT NULL DEFAULT 0,
    received_at TIMESTAMP(6) NOT NULL,
    processed_at TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_callback_provider_event (provider, provider_event_id),
    KEY idx_payment_callback_claim (status, lease_until),
    CONSTRAINT ck_payment_callback_status CHECK (status IN ('RECEIVED', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_payment_callback_attempts CHECK (attempt_count >= 0),
    CONSTRAINT fk_payment_callback_payment_order FOREIGN KEY (payment_order_id) REFERENCES payment_order (id)
);

CREATE TABLE refund_order (
    id CHAR(36) NOT NULL,
    order_id CHAR(36) NOT NULL,
    payment_order_id CHAR(36) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id CHAR(36),
    paid_amount_fen BIGINT NOT NULL,
    amount_fen BIGINT NOT NULL,
    successful_refund_fen BIGINT NOT NULL DEFAULT 0,
    reserved_refund_fen BIGINT NOT NULL DEFAULT 0,
    provider_reference VARCHAR(191),
    status VARCHAR(24) NOT NULL,
    next_reconcile_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_refund_idempotency (order_id, idempotency_key),
    UNIQUE KEY uk_refund_provider_reference (provider, provider_reference),
    KEY idx_refund_reconcile (status, next_reconcile_at),
    KEY idx_refund_order_amounts (order_id, status, paid_amount_fen),
    CONSTRAINT ck_refund_paid_amount CHECK (paid_amount_fen >= 0),
    CONSTRAINT ck_refund_order_amount CHECK (amount_fen >= 0),
    CONSTRAINT ck_refund_successful_amount CHECK (successful_refund_fen >= 0),
    CONSTRAINT ck_refund_reserved_amount CHECK (reserved_refund_fen >= 0),
    CONSTRAINT ck_refund_amount_le_paid CHECK (amount_fen <= paid_amount_fen),
    CONSTRAINT ck_refund_successful_le_paid CHECK (successful_refund_fen <= paid_amount_fen),
    CONSTRAINT ck_refund_reserved_le_paid CHECK (reserved_refund_fen <= paid_amount_fen),
    CONSTRAINT ck_refund_reserved_plus_success_le_paid CHECK (reserved_refund_fen + successful_refund_fen <= paid_amount_fen),
    CONSTRAINT ck_refund_total_le_paid CHECK (reserved_refund_fen + successful_refund_fen + amount_fen <= paid_amount_fen),
    CONSTRAINT ck_refund_order_status CHECK (status IN ('REQUESTED', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT fk_refund_order_order FOREIGN KEY (order_id) REFERENCES trade_order (id),
    CONSTRAINT fk_refund_order_payment FOREIGN KEY (payment_order_id) REFERENCES payment_order (id)
);

CREATE TABLE settlement (
    id CHAR(36) NOT NULL,
    order_id CHAR(36) NOT NULL,
    paid_amount_fen BIGINT NOT NULL,
    successful_refund_fen BIGINT NOT NULL DEFAULT 0,
    net_settlement_fen BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_settlement_order (order_id),
    CONSTRAINT ck_settlement_paid CHECK (paid_amount_fen >= 0),
    CONSTRAINT ck_settlement_refund CHECK (successful_refund_fen >= 0 AND successful_refund_fen <= paid_amount_fen),
    CONSTRAINT ck_settlement_net CHECK (net_settlement_fen >= 0 AND net_settlement_fen <= paid_amount_fen),
    CONSTRAINT ck_settlement_status CHECK (status IN ('PENDING', 'SETTLED', 'BLOCKED')),
    CONSTRAINT fk_settlement_order FOREIGN KEY (order_id) REFERENCES trade_order (id)
);

ALTER TABLE inventory_movement
    ADD CONSTRAINT fk_inventory_movement_order FOREIGN KEY (order_id) REFERENCES trade_order (id);
