spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:${MYSQL_PORT:3307}/${MYSQL_DATABASE:security_rbac}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:security_app}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:}
  access-token-ttl: 900
  refresh-token-ttl: 604800

server:
  port: ${SERVER_PORT:8080}
